config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :main do
    resources :restaurants
  end
  get 'menu_item/new/:restaurant_id', to: 'menu_item#new', as: 'new_menu_item'
  post 'menu_item/create/:restaurant_id', to: 'menu_item#create', as: 'create_menu_item'
  resources :menu_item

  get 'profile',to: 'profile#show'

  # get 'main',to: 'main#new'
  # get 'menu_item',to:'menu_item#show'
  post 'menu_item',to:'cart_item#add_cart_items'

  get 'cart_item', to: 'cart_item#show'

  devise_for :user, controllers: { registrations: 'user/registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @restaurant_all=Restaurant.all.paginate(page: params[:page])
  end
  #creating a variable for the common form so that we know which model is being accessed
  def new
    @resource=Restaurant.new
  end
  #for creating a new restaurant
  def create
    if Main::RestaurantCreator.new(restaurant_params).create
      redirect_to root_path, notice: "Restaurant added successfully"
    else
      render :new
    end
  end

  #for updating
  def edit
        @resto=Restaurant.find_by(id: params[:id])
  end

  def update
    updater = Main::RestaurantUpdater.new(params[:id],restaurant_params)
    if updater.update
      redirect_to root_path, notice: "Restaurant updated successfully"
    else
      redirect_to root_path, notice: "Restaurant could not be updated"
    end
  end
  #for destroying
  def destroy
    restaurant_creator = Main::RestaurantDestroyer.new(params[:id])
    restaurant = restaurant_creator.destroy
    if restaurant.errors.blank?
      redirect_to root_path, notice: "Restaurant deleted successfully"
    else
      redirect_to root_path, notice: "Could not delete Restaurant"
    end
  end

  #private methods
  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :email, :phno,:image)
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/edit.html.erb
<%= render 'shared/edit_form', resource: Restaurant.new%>

app/views/main/index.html.erb
<html>
<head>
<%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<% if current_user && current_user.isadmin%>
    <h1>hello Admin</h1>
    <%=button_to "Add Restaurant",new_main_path,method: :get%>

    <%@restaurant_all.each do |resto|%>
        <div class="main_cont">
            <div class="image">
                 <% if resto.image.present? %>
                     <%=image_tag url_for(resto.image),style:"height:120px;width:120px;"%>
                 <% else %>
                    <p>No image available</p>
                 <% end %>
                 </div> 
            <div class="cont">
                <p>Name:<%=resto.name%></p>
                <p>Email:<%=resto.email%></p>
                <p>Phone Number:<%=resto.phno%></p>
            </div>
            <div class="btn">
                    <%= button_to "Select",menu_item_path(resto.id), method: :get,class:"btn_in"%>
                    <%= button_to "Edit", edit_main_path(resto.id), method: :get, class: "btn_in" %>
                    <%= button_to "Delete",main_path(resto.id),method: :delete,class:"btn_in"%>
            </div>
           
        </div>
       
    <%end%>
     <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @restaurant_all %>
    </div>
    <div class="center-a">
    <%= will_paginate @restaurant_all, :container => false %>
    <div>
  </div>
<%else%>
    <% if user_signed_in?%>
        <h1>hello <%=current_user.username%></h1>
        <%@restaurant_all.each do |resto|%>
            <div class="main_cont">
             <div class="image">
                 <% if resto.image.present? %>
                     <%=image_tag url_for(resto.image),style:"height:120px;width:120px;"%>
                 <% else %>
                    <p>No image available</p>
                 <% end %>
              </div> 
            <div class="cont">
                <p>Name:<%=resto.name%></p>
                <p>Email:<%=resto.email%></p>
                <p>Phone Number:<%=resto.phno%></p>
            </div>
            <div class="btn">
                    <%= button_to "Select",menu_item_path(resto), method: :get%>
                </div>
            </div>
        <%end%>
        <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @restaurant_all %>
    </div>
    <div class="center-a">
    <%= will_paginate @restaurant_all, :container => false %>
    <div>
  </div>
    <%end%>
<%end%>
</body>
</html>

app/views/main/new.html.erb
<%= render 'shared/create_form', resource: Restaurant.new%>