config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :main do
    resources :restaurants
  end
  get 'menu_item/new/:restaurant_id', to: 'menu_item#new', as: 'new_menu_item'
  post 'menu_item/create/:restaurant_id', to: 'menu_item#create', as: 'create_menu_item'
  resources :menu_item

  get 'profile',to: 'profile#show'

  # get 'main',to: 'main#new'
  # get 'menu_item',to:'menu_item#show'
  post 'menu_item',to:'cart_item#add_cart_items'

  get 'cart_item', to: 'cart_item#show'

  devise_for :user, controllers: { registrations: 'user/registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  self.per_page = 5
  belongs_to :restaurant
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_one_attached :image

end

app/controllers/menu_item_controller.rb
class MenuItemController < ApplicationController
  def show
    @resto = Restaurant.find_by(id: params[:id])
    if @resto
      @menus = @resto.menu_items.paginate(page: params[:page])
    else
      redirect_to root_path, notice: "No restaurants found"
    end
  end

  def new
    @resto = Restaurant.find_by(id: params[:restaurant_id])
    @resource = MenuItem.new
  end


  def create
    @resto = Restaurant.find_by(id: params[:restaurant_id])

    if @resto
      menu_creator = Menu::MenuCreator.new(menu_params.merge(restaurant_id: @resto.id))

      if menu_creator.create
        redirect_to menu_item_path(id: @resto.id), notice: "Menu Item added successfully"
      else
        render :new
      end
    else
      redirect_to root_path, notice: "Restaurant not found"
    end
  end


  private
  def menu_params
    params.require(:menu_item).permit(:name, :item_price,:image)
  end

end

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/views/menu_item/list.html.erb
<html>
<head>
<%= stylesheet_link_tag 'menu_item', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<% @menus.each do |menu| %>
    <div class="main_cont">
        <div class="cont">
        <p> <%=menu.name%> </p>
        <p> <%=menu.item_price%> </p>
        </div>
        <div class="btn">
            <%= button_to "Add", menu_item_path,params:{menu_item_id: menu.id,restaurant_id: menu.restaurant.id},method: :post%>
        </div> 
        </div>
<%end%>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @menus %>
    </div>
    <div class="center-a">
    <%= will_paginate @menus, :container => false %>
    <div>
  </div>
  </body>
</html>

app/views/menu_item/new.html.erb
<%= render 'shared/create_form' ,resource: MenuItem.new%>

app/views/menu_item/show.html.erb
<html>
<head>
<%= stylesheet_link_tag 'menu_item', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= button_to 'Add Menu Item',new_menu_item_path(restaurant_id: @resto.id),method: :get%>
<% @menus.each do |menu| %>
    <div class="main_cont">
        <div class="image">
            <% if menu.image.present? %>
              <%= image_tag(url_for(menu.image), style: "height:120px;width:120px;") %>
            <% else %>
              <p>No image available</p>
            <% end %>
        </div> 
        <div class="cont">
            <p><%= menu.name %></p>
            <p><%= menu.item_price %></p>
        </div>
        <div class="btn">
            <%= button_to "Add", menu_item_path, params: { menu_item_id: menu.id, restaurant_id: menu.restaurant.id }, method: :post,class:"btn_in" %>
            <%= button_to "Edit",menu_item_path,class:"btn_in"%>
            <%= button_to "Delete",menu_item_path,class:"btn_in"%>
        </div> 
    </div>
<% end %>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @menus %>
    </div>
    <div class="center-a">
    <%= will_paginate @menus, :container => false %>
    <div>
  </div>
  </body>
</html>