config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :main do
    resources :restaurants
  end
  get 'menu_item/new/:restaurant_id', to: 'menu_item#new', as: 'new_menu_item'
  post 'menu_item/create/:restaurant_id', to: 'menu_item#create', as: 'create_menu_item'
  resources :menu_item

  get 'profile',to: 'profile#show'

  # get 'main',to: 'main#new'
  # get 'menu_item',to:'menu_item#show'
  post 'menu_item',to:'cart_item#add_cart_items'

  get 'cart_item', to: 'cart_item#show'

  devise_for :user, controllers: { registrations: 'user/registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items,dependent: :destroy
  has_many :menu_items,through: :cart_items

  attribute :completed, :boolean, default: false
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu_item
  attribute :quantity, :integer, default: 1

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  self.per_page = 5
  belongs_to :restaurant
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_one_attached :image

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  self.per_page=5
  has_many :menu_items, dependent: :destroy
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :name
  attribute :isadmin, :boolean, default: false
  has_many :carts, dependent: :destroy
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_to_create_cart

  protected
  def check_to_create_cart
    if user_signed_in?
      if (current_user.carts.exists?(completed:true) || !current_user.carts.exists?) && !current_user.isadmin
          current_user.carts.create
      end
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cart_item_controller.rb
class CartItemController < ApplicationController
  before_action :check_active_cart
  def show
    @cart_items=current_user.carts.last.cart_items
  end
  def add_cart_items
    if @active_cart.present?
      result=MyCartItem::CartAddUpdate.new(@active_cart,params[:menu_item_id]).add_or_update_items
      if result[:success]
        redirect_to menu_item_path(restaurant_id: params[:restaurant_id])
        flash[:notice]=result[:message]
      else
        redirect_to menu_item_path(restaurant_id: params[:restaurant_id])
        flash[:alert]=result[:message]
      end
    end
  end
  
  private
  def check_active_cart
    @carts = current_user.carts
    @active_cart=@carts.find_by(completed: false)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @restaurant_all=Restaurant.all.paginate(page: params[:page])
  end
  #creating a variable for the common form so that we know which model is being accessed
  def new
    @resource=Restaurant.new
  end
  #for creating a new restaurant
  def create
    if Main::RestaurantCreator.new(restaurant_params).create
      redirect_to root_path, notice: "Restaurant added successfully"
    else
      render :new
    end
  end

  #for updating
  def edit
        @resto=Restaurant.find_by(id: params[:id])
  end

  def update
    updater = Main::RestaurantUpdater.new(params[:id],restaurant_params)
    if updater.update
      redirect_to root_path, notice: "Restaurant updated successfully"
    else
      redirect_to root_path, notice: "Restaurant could not be updated"
    end
  end
  #for destroying
  def destroy
    restaurant_creator = Main::RestaurantDestroyer.new(params[:id])
    restaurant = restaurant_creator.destroy
    if restaurant.errors.blank?
      redirect_to root_path, notice: "Restaurant deleted successfully"
    else
      redirect_to root_path, notice: "Could not delete Restaurant"
    end
  end

  #private methods
  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :email, :phno,:image)
  end
end

app/controllers/menu_item_controller.rb
class MenuItemController < ApplicationController
  def show
    @resto = Restaurant.find_by(id: params[:id])
    if @resto
      @menus = @resto.menu_items.paginate(page: params[:page])
    else
      redirect_to root_path, notice: "No restaurants found"
    end
  end

  def new
    @resto = Restaurant.find_by(id: params[:restaurant_id])
    @resource = MenuItem.new
  end


  def create
    @resto = Restaurant.find_by(id: params[:restaurant_id])

    if @resto
      menu_creator = Menu::MenuCreator.new(menu_params.merge(restaurant_id: @resto.id))

      if menu_creator.create
        redirect_to menu_item_path(id: @resto.id), notice: "Menu Item added successfully"
      else
        render :new
      end
    else
      redirect_to root_path, notice: "Restaurant not found"
    end
  end


  private
  def menu_params
    params.require(:menu_item).permit(:name, :item_price,:image)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user && current_user.isadmin%>
    <%= render partial:"shared/adminbar"%>
    <%else%>
        <%= render partial:"shared/navbar"%>
    <%end%>
    <%= render partial:"shared/flash"%> 
    <%= yield %>
  </body>
</html>

app/views/shared/_adminbar.html.erb
<style>
.navbar {
 position: relative;
 
  width: 100%;
  background-color: #666666;
  color: black;
  text-align: center;
  padding: 10px;
}
</style>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
          
            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_create_form.html.erb
<%= form_for(resource, url: (@resource.is_a?(MenuItem) ? {controller: 'menu_item', action: 'create'} : {controller: 'main', action: 'create'})) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <% if @resource.is_a?(Restaurant) %>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
     <div class="field">
        <%= form.label :phno %>
        <%= form.text_field :phno %>
    </div>
    
  <%end%>
  <%if @resource.is_a?(MenuItem)%>
  <%= form.hidden_field :restaurant_id, value: @resto.id if @resto.present? %>
    <div class="field">
        <%= form.label :item_price %>
        <%= form.text_field :item_price %>
    </div>
  <%end%>
  <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image %>
    </div>
  <%= form.submit %>
<% end %>

app/views/shared/_edit_form.html.erb
<%= form_for @resto, url: { action: "update", id: @resto .id }, method: :patch do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :phno %>
    <%= f.text_field :phno %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit %>
<% end %>

app/views/shared/_flash.html.erb
<script>
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        $("#notice, #alert").fadeOut("slow", function() {
            $(this).remove(); // Remove the element after fading out
        });
    }, 2000); // Fade out messages after 3 seconds (adjust as needed)
});
</script>

<% if flash[:notice] %>
<div id="notice" class="alert alert-info mt-4"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
<div id="alert" class="alert alert-warning mt-4"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_form.html.erb
<%= form_for(@resource, url: {controller: 'main', action: 'create'})  do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <% if @resource.is_a?(Restaurant) %>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
     <div class="field">
        <%= form.label :phno %>
        <%= form.text_field :phno %>
    </div>
    <div class="field">
        <%= form.label :restaurant_image %>
        <%= form.file_field :restaurant_image %>
    </div>
  <%end%>
  <%if @resource.is_a?(MenuItem)%>
     <div class="field">
        <%= form.label :item_price %>
        <%= form.text_field :item_price %>
    </div>

  <%end%>
  <%= form.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<style>
.navbar {
 position: relative;
 
  width: 100%;
  background-color: #666666;
  color: black;
  text-align: center;
  padding: 10px;
}
</style>

<nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Ziigs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home',root_path,class:"nav-link"%>
        </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if !user_signed_in?%>
        <% unless params[:controller] == "devise/sessions" && params[:action] == "new" %>
        <li class="nav-item">
          <%= link_to 'SignIn',user_session_path,class:"nav-link"%>
        </li>
        <%end%>
        <% unless params[:controller] == "user/registrations" && params[:action] == "new" %>
        <li class="nav-item">
          <%= link_to 'SignUp',new_user_registration_path,class:"nav-link"%>
        </li>
        <%end%>
        <%end%>
        <% if user_signed_in? %>
            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to profile_path, class: "nav-link" do %>
                <i class='fas fa-user-alt' style='font-size:20px;color:black'></i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to cart_item_path, class: "nav-link" do %>
                <i class="fa fa-shopping-cart" style="font-size:20px;color:black"></i>
              <% end %>
            </li>
        <% end %>

      </ul>
      
    </div>
  </div>
</nav>